apiVersion: v1
kind: Pod
metadata:
  name: redis
  annotations:
    net.v1.intel.com/adq-config: '[ { "name": "redis", "ports": { "local": ["6379/  TCP"] } } ]'
spec:
  nodeSelector:
    kubernetes.io/hostname: hostname
  containers:
    - name: redis
      image: redis:latest
      command:
        - redis-server
        - "/redis-master/redis.conf"
      ports:
        - containerPort: 6379
      resources:
        limits:
          net.intel.com/adq: 1
      volumeMounts:
        - mountPath: /redis-master-data
          name: data
        - mountPath: /redis-master
          name: config
  volumes:
    - name: data
      emptyDir: {}
    - name: config
      configMap:
        name: example-redis-config
        items:
          - key: redis-config
            path: redis.conf
